# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: VM-AWS

steps:
- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: '$(ScanCentralURL)'
    scanCentralClientToken: '$(ScanCentral.ClientToken)'
    sscUrl: '$(ScanCentral.ClientToken)'
    sscCiToken: '$(ScanCentral.SscCiToken)'
    uploadToSSC: true
    applicationName: '$(SSC_PROJECTNAME)'
    applicationVersion: '$(SSC_PROJECTVERSION)'
    buildTool: 'msbuild'
    buildCommand: 'rebuild'
    buildFile: 'csharp.sln'
    block: true
    outputFile: 'csharp.fpr'
    logFile: 'charp.log'
    overwrite: true

